### ISSUE TITLE
Negative throughputs from BUs

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQAggregator#91] opened 2017-06-19 18:14 UTC
Hi,

there is a problem with mapping the unsigned long values from the BUs for the throughput in the aggregator. The values in the flashlist show e.g. '3286449865' Bytes/s, while the aggregator snapshot contains number like '-1132031326'.

Remi

**Comment by andreh12** [comment] 2017-06-19 19:24
taking the BU flashlist and the aggregator snapshot at the same point in time:

- `/daqexpertflashlists/flashlists-dev/persistence/testbed/flashlists/BU/2017/6/19/19/1497899617932.smile`
- `/daqexpert/snapshots/dev/testbed/2017/6/19/19/1497899617932.smile`

one sees for an example `bu-c2e18-29-01` the following:
- "throughput" : 3294648689 in the flashlist .smile file
- "throughput" : -1000318607 in the DAQAggregator snapshot .smile file

in 32 bit two's complement hex these are:
- 3294648689 = 0xc4605971
- -1000318607 = 0xc4605971

so there seems to be (as you probably guessed it) some restriction to 32 bit going on even though the field `BU.throughput` is long (as well as the corresponding setter and getter).

**Comment by andreh12** [comment] 2017-06-19 19:32
the problem is probably here: https://github.com/cmsdaq/DAQAggregator/blob/6acb38bf07f9d7a3283969f62add774f4608e6ba/src/main/java/rcms/utilities/daqaggregator/data/BU.java#L124 which should be `.asLong()` instead of `.asInt()` (the same also holds for the field `rate`).

**Comment by m-gl** [comment] 2017-06-20 07:58
@mommsen thank you for reporting this problem, @andreh12 thank you for pinpointing the bug. The  hotfix is ready to be deployed as 1.13.1. Right now we have stable beams, @mommsen should I deploy it now or you want me to wait for interfill period?

**Comment by mommsen** [comment] 2017-06-20 08:00
Please wait for the next interfill period.

**Comment by m-gl** [comment] 2017-06-20 09:31
The hotfixed DAQAggregator 1.13.1 was successfully deployed to production at 11:23. Closing the issue.

**Closed as completed by m-gl** 2017-06-20 09:31 UTC
